[versions]
androidTools = "31.1.1"

[libraries]
clikt = "com.github.ajalt.clikt:clikt:5.0.3"

androidTools-common = { module = "com.android.tools:common", version.ref = "androidTools" }
androidTools-sdkCommon = { module = "com.android.tools:sdk-common", version.ref = "androidTools" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "1.9.10" }
